const SELECT_COURSE = 'SELECT_COURSE';
const UNSELECT_COURSE = 'UNSELECT_COURSE';
const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';
const SET_COURSES = 'SET_COURSES';
export {
    SELECT_COURSE,
    UNSELECT_COURSE,
    FETCH_COURSE_SUCCESS,
    SET_COURSES
  };