const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const DISPLAY_NOTIFICATION_DRAWER = 'DISPLAY_NOTIFICATION_DRAWER';
const HIDE_NOTIFICATION_DRAWER= 'HIDE_NOTIFICATION_DRAWER';


export {
    LOGIN,
    LOGOUT,
    DISPLAY_NOTIFICATION_DRAWER,
    HIDE_NOTIFICATION_DRAWER
  };