const LOGIN = 'root/LOGIN';
const LOGOUT = 'root/LOGOUT';
const DISPLAY_NOTIFICATION_DRAWER = 'root/DISPLAY_NOTIFICATION_DRAWER';
const HIDE_NOTIFICATION_DRAWER= 'root/HIDE_NOTIFICATION_DRAWER';


export {
    LOGIN,
    LOGOUT,
    DISPLAY_NOTIFICATION_DRAWER,
    HIDE_NOTIFICATION_DRAWER
  };